Exposed volume prop in HowlOptions
StefH/Howler.Blazor pull request #18
Opened 2021-05-31 09:24 UTC by k-u-s

Resolves #17,

Added Volume property to HowlOptions and added Play half and 1/4 buttons to sample apps.

2021-05-31 09:48 UTC, StefH requested changes
Please take a look at my comments

2021-05-31 09:48 UTC, StefH commented on examples/Howler.Blazor-AudioPlayer/Pages/Example.razor
> +            <td><button class="btn btn-primary oi oi-media-play" @onclick="PlayHalf"></button></td>
Can you rename `PlayHalf` to `PlayAudioWithHalfVolume` in all code?

2021-05-31 09:48 UTC, StefH commented on examples/Howler.Blazor-AudioPlayer/Pages/Example.razor
> +            <td><button class="btn btn-primary oi oi-media-play" @onclick="PlayQuoter"></button></td>
Can you rename `PlayQuoter` to `PlayAudioWithQuarterVolume` in all code?

2021-05-31 13:38 UTC, k-u-s commented on examples/Howler.Blazor-AudioPlayer/Pages/Example.razor
> +            <td><button class="btn btn-primary oi oi-media-play" @onclick="PlayQuoter"></button></td>
Done in https://github.com/StefH/Howler.Blazor/pull/18/commits/f609ccb4cf03709844d67fca14b29a1a00a91662

2021-05-31 13:38 UTC, k-u-s commented on examples/Howler.Blazor-AudioPlayer/Pages/Example.razor
> +            <td><button class="btn btn-primary oi oi-media-play" @onclick="PlayHalf"></button></td>
Done in https://github.com/StefH/Howler.Blazor/pull/18/commits/f609ccb4cf03709844d67fca14b29a1a00a91662

2021-06-01 07:13 UTC, StefH approved these changes

2021-06-01 07:13 UTC, merged